spring:
  profiles:
    active: develop
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  thymeleaf:
    cache: false
  security:
    user:
      name: Admin
      password: Admin
---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: "jdbc:postgresql://localhost:5441/postgres"
    username: postgres
    password: postgres
server:
  port: 8080
  servlet:
    off_context-path: /app
---
spring:
  config:
    activate:
      on-profile: nii-deploy
  datasource:
    url: "jdbc:postgresql://192.168.0.98:5432/postgres"
    username: postgres
    password: postgres
server:
  port: 8080

